/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elevatorsimulation;



/**
 *
 * @author 2ndyrGroupB
 */
public class Elevator extends javax.swing.JFrame {
        FloorA fa = new FloorA();
        FloorB fb = new FloorB();
        FloorC fc = new FloorC();
        FloorD fd = new FloorD();
        FloorE fe = new FloorE();
        FloorF ff = new FloorF();
        RequestArray my = new RequestArray(20);
   
    public Elevator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnsecond = new javax.swing.JButton();
        btngf = new javax.swing.JButton();
        btnfourth = new javax.swing.JButton();
        btnthird = new javax.swing.JButton();
        btnfifth = new javax.swing.JButton();
        btnsixth = new javax.swing.JButton();
        indicator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Floor Control");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnsecond.setBackground(new java.awt.Color(255, 255, 255));
        btnsecond.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnsecond.setText("2");
        btnsecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsecondActionPerformed(evt);
            }
        });

        btngf.setBackground(new java.awt.Color(255, 255, 255));
        btngf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btngf.setText("GF");
        btngf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngfActionPerformed(evt);
            }
        });

        btnfourth.setBackground(new java.awt.Color(255, 255, 255));
        btnfourth.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnfourth.setText("4");
        btnfourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfourthActionPerformed(evt);
            }
        });

        btnthird.setBackground(new java.awt.Color(255, 255, 255));
        btnthird.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnthird.setText("3");
        btnthird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthirdActionPerformed(evt);
            }
        });

        btnfifth.setBackground(new java.awt.Color(255, 255, 255));
        btnfifth.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnfifth.setText("5");
        btnfifth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfifthActionPerformed(evt);
            }
        });

        btnsixth.setBackground(new java.awt.Color(255, 255, 255));
        btnsixth.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnsixth.setText("6");
        btnsixth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsixthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btngf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnsecond, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnfifth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnsixth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnthird, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btnfourth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfifth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsixth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthird, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfourth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsecond, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        indicator.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        indicator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indicator.setText("Floor Indicator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(indicator, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(indicator, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsecondActionPerformed
        // TODO add your handling code here:
        
        fb.sendMessage("2nd Floor");
        fa.sendMessage("2nd Floor");
        fc.sendMessage("2nd Floor");
        fd.sendMessage("2nd Floor");
        fe.sendMessage("2nd Floor");
        ff.sendMessage("2nd Floor");
        indicator.setText("2nd Floor");
        my.addMessage("2nd Floor");
//        this.dispose();
//        sendData("2nd Floor");    
    }//GEN-LAST:event_btnsecondActionPerformed

    private void btnfourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfourthActionPerformed
        // TODO add your handling code here:
//        FloorA fa = new FloorA();
//        FloorB fb = new FloorB();
        fb.sendMessage("4th Floor");
        fa.sendMessage("4th Floor");
        fc.sendMessage("4th Floor");
        fd.sendMessage("4th Floor");
        fe.sendMessage("4th Floor");
        ff.sendMessage("4th Floor");
        indicator.setText("4th Floor");
        my.addMessage("4th Floor");
//        this.dispose();
//        sendData("4th Floor");
    }//GEN-LAST:event_btnfourthActionPerformed

    private void btnthirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthirdActionPerformed
        // TODO add your handling code here:
//        FloorA fa = new FloorA();
//        FloorB fb = new FloorB();
        fb.sendMessage("3rd Floor");
        fa.sendMessage("3rd Floor");
        fc.sendMessage("3rd Floor");
        fd.sendMessage("3rd Floor");
        fe.sendMessage("3rd Floor");
        ff.sendMessage("3rd Floor");
        indicator.setText("3rd Floor");
        my.addMessage("3rd Floor");
        
//        sendData("3rd Floor");
    }//GEN-LAST:event_btnthirdActionPerformed

    private void btnfifthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfifthActionPerformed
        // TODO add your handling code here:
//        FloorA fa = new FloorA();
//        FloorB fb = new FloorB();
        fb.sendMessage("5th Floor");
        fa.sendMessage("5th Floor");
        fc.sendMessage("5th Floor");
        fd.sendMessage("5th Floor");
        fe.sendMessage("5th Floor");
        ff.sendMessage("5th Floor");
        indicator.setText("5th Floor");
        my.addMessage("5th Floor");
//        this.dispose();
//        sendData("5th Floor");
    }//GEN-LAST:event_btnfifthActionPerformed

    private void btnsixthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsixthActionPerformed
        // TODO add your handling code here:
//        FloorA fa = new FloorA();
//        FloorB fb = new FloorB();
        fb.sendMessage("6th Floor");
        fa.sendMessage("6th Floor");
        fc.sendMessage("6th Floor");
        fd.sendMessage("6th Floor");
        fe.sendMessage("6th Floor");
        ff.sendMessage("6th Floor");
        indicator.setText("6th Floor");
        my.addMessage("6th Floor");
//        this.dispose();
//        message ="6th Floor";
//        sendData(message);
    }//GEN-LAST:event_btnsixthActionPerformed

    private void btngfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngfActionPerformed
        // TODO add your handling code here:
//        FloorA fa = new FloorA();
//        FloorB fb = new FloorB();
        fb.sendMessage("Ground Floor");
        fa.sendMessage("Ground Floor");
        fc.sendMessage("Ground Floor");
        fd.sendMessage("Ground Floor");
        fe.sendMessage("Ground Floor");
        ff.sendMessage("Ground Floor");
        indicator.setText("Ground Floor");
        my.addMessage("Ground Floor");
//        this.dispose();
//        sendData("Ground Floor");
    }//GEN-LAST:event_btngfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elevator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elevator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elevator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elevator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elevator().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JButton btnfifth;
    static javax.swing.JButton btnfourth;
    static javax.swing.JButton btngf;
    static javax.swing.JButton btnsecond;
    static javax.swing.JButton btnsixth;
    static javax.swing.JButton btnthird;
    static javax.swing.JLabel indicator;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
